### ISSUE TITLE
Crash when use Accompanist 0.10.0 with compose-beta07

### ISSUE THREAD

**Issue by kraizman** [google/accompanist#427]
## Describe the bug
After the update of compose to beta07 and accompanist to v0.10.0, i started to get `NoSuchMethodError: No interface method startReplaceableGroup`. This is exactly what [Release notes](https://developer.android.com/jetpack/androidx/releases/compose-ui#1.0.0-beta07) mention

```
Note: Libraries dependent on Compose will need to recompile with version 1.0.0‑beta07. Otherwise, libraries may encounter a NoSuchMethodError, such as:
java.lang.NoSuchMethodError: No interface method startReplaceableGroup(ILjava/lang/String;)V in class Landroidx/compose/runtime/Composer; or its super classes. (Ia34e6)
```

## To Reproduce
It fails on app launch with the crash:

```
2021-05-20 08:39:30.135 30316-30316/com.pasha.hitsradio2 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.pasha.hitsradio2, PID: 30316
    java.lang.NoSuchMethodError: No interface method startReplaceableGroup(ILjava/lang/String;)V in class Landroidx/compose/runtime/Composer; or its super classes (declaration of 'androidx.compose.runtime.Composer' appears in /data/app/com.pasha.hitsradio2-pwwK1WHFQDVrdnF6YcxJ8g==/base.apk)
        at com.pasha.hitsradio2.ui.home.HomeKt.Home(Home.kt:49)
        at com.pasha.hitsradio2.ComposableSingletons$MainActivityKt$lambda-2$1.invoke(MainActivity.kt:53)
        at com.pasha.hitsradio2.ComposableSingletons$MainActivityKt$lambda-2$1.invoke(MainActivity.kt:52)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.material.SurfaceKt$Surface$1.invoke(Surface.kt:119)
        at androidx.compose.material.SurfaceKt$Surface$1.invoke(Surface.kt:108)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:193)
        at androidx.compose.material.SurfaceKt.Surface-F-jzlyU(Surface.kt:105)
        ...
```

## Environment:
 - Android OS version: [e.g. Android 10.0]
 - Device: Emulator
 - Accompanist version: v0.10.0

## Additional context
I am using dependencies:

```
    implementation("com.google.accompanist:accompanist-insets:${Versions.accompanistVersion}")
    implementation("com.google.accompanist:accompanist-glide:${Versions.accompanistVersion}")
```

If I revert the version back of compose and accompanist to beta06 and 0.9.1 all woks as expected

**Comment by chrisbanes** [comment]
As per the [docs](https://developer.android.com/jetpack/androidx/releases/compose-runtime#version_100_2), you need to upgrade all of your Compose libraries. This isn’t an Accompanist bug.

**Comment by kraizman** [comment]
You were right. The issue in my case was koin-compose lib
