### PR TITLE
[Documentation] Update Dokka to 1.8.10, Fix search

### LINKED ISSUE #1533: Search is broken on some pages of the documentation
## To Reproduce (if applicable)
* Go to https://google.github.io/accompanist/insets/
* Try to search something using the search form in the header

Search will get stuck on the "Initializing search" phase. 

Javascript error in console:
```
reportUnhandledError.ts:21 Uncaught ReferenceError: Missing element: expected ".tabbed-labels" to be present
    at V (index.ts:77:11)
    at Do (index.ts:136:21)
    at index.ts:114:21
    at Array.map (<anonymous>)
    at Vo (index.ts:114:8)
    at bundle.ts:250:16
    at Array.map (<anonymous>)
    at bundle.ts:250:6
    at e._subscribe (defer.ts:55:15)
    at e._trySubscribe (Observable.ts:244:19)
```
The same behavior is observed on some other pages too, while on the [front page](https://google.github.io/accompanist/) search works properly. 
This issue may be related: https://github.com/squidfunk/mkdocs-material/issues/3327. 
"Publish docs" workflow always installs the latest version of the mkdocs and it is quite possible that a major update might not have been noticed.

### PR DESCRIPTION
**Pull request by illarionov**
#### Update Dokka to 1.8.10
This fixes the NoSuchMethodError exception when running the `dokkaHtmlMultiModule` task that appeared after upgrading Gradle to 8.1 (https://github.com/Kotlin/dokka/issues/2796). 
This also brings a new UI for the API documentation pages.

#### Fixed search on documentation page
Turned on alternate style on the Tabbed extension of the `mkdocs-material` to fix search on internal doc pages (fixes #1533). 
Also locked the major version of the `mkdocs-material` to prevent uncontrolled updates in the future and added the `gradle/gradle-build-action@v2` action to the publishing documentation workflow as in other workflows

### CODE REVIEW

**Review by bentrengrove — APPROVED** [review]
Thank you for the contribution! This looks like a great improvement
